server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/incomesvcdb
    username: postgres
    password: tore1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
